from fpdf import FPDF
import os
import json
from datetime import datetime

class FormGenerator:
    """
    Generates pre-filled government application forms as PDFs.
    Uses templates/metadata for different service types.
    """
    def __init__(self):
        self.output_dir = "backend/app/temp_forms"
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, service_type, user_data):
        """
        Generates a PDF for the specified service type using a template if available.
        """
        template_path = f"backend/app/data/forms/{service_type}.json"
        template = None
        if os.path.exists(template_path):
            with open(template_path, "r") as f:
                template = json.load(f)

        filename = f"{service_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        pdf = FPDF()
        pdf.add_page()
        
        # Header - Gov Style
        dept_name = template.get("department", "GOVERNMENT OF KERALA") if template else "GOVERNMENT OF KERALA"
        form_name = template.get("form_name", f"Application for {service_type.replace('_', ' ').title()}") if template else f"APPLICATION FOR {service_type.replace('_', ' ').title()}"

        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "GOVERNMENT ASSISTANCE SERVICE", ln=True, align="C")
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 8, dept_name.upper(), ln=True, align="C")
        pdf.ln(5)
        
        # Form Title
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_fill_color(220, 230, 241) # Light blue header
        pdf.cell(0, 12, form_name.upper(), ln=True, align="C", fill=True)
        pdf.ln(10)
        
        # Content
        pdf.set_font("Helvetica", "", 12)
        
        if template:
            for field in template.get("fields", []):
                fid = field["id"]
                label = field["label"]
                value = user_data.get(fid, "________________")
                
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(50, 50, 50)
                pdf.cell(0, 8, label.upper(), ln=True)
                
                pdf.set_font("Helvetica", "", 12)
                pdf.set_text_color(0, 0, 0)
                if field.get("type") == "textarea":
                    pdf.multi_cell(0, 10, str(value), border="B")
                else:
                    pdf.cell(0, 10, str(value), border="B", ln=True)
                pdf.ln(4)
        else:
            # Fallback for generic data
            for key, value in user_data.items():
                label = key.replace("_", " ").title() + ":"
                pdf.set_font("Helvetica", "B", 12)
                pdf.cell(60, 10, label, border=0)
                pdf.set_font("Helvetica", "", 12)
                pdf.cell(0, 10, str(value), border="B", ln=True)
                pdf.ln(2)
            
        pdf.ln(15)
        
        # Declaration
        decl_text = template.get("declaration", "I hereby declare that all the information provided above is true to the best of my knowledge and belief. I understand that providing false information is a punishable offense.") if template else "I hereby declare that all the information provided above is true."
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 5, f"Declaration: {decl_text}")
        
        pdf.ln(25)
        
        # Signature spaces
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(90, 10, "Signature of Applicant", align="L")
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d/%m/%Y')}", align="R", ln=True)
        
        # Branding
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Generated by NYAANA-VAAS AI KIOSK • Akshaya Digital Support", align="C")

        pdf.output(filepath)
        return filepath, filename
